name: Build Figma-Chat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build
